########################################
###          HOME ASSISTANT          ###
########################################
default_config:
homeassistant:
  time_zone: !secret zone_home_time_zone
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  packages: !include_dir_named packages
  customize: !include customize.yaml
frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
  resources: !include lovelace/includes/resources.yaml

########################################
###              LOGGING             ###
########################################
recorder:
  db_url: !secret mariadb
  purge_keep_days: 2
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

########################################
###              SERVICE             ###
########################################
badnest:
  issue_token: !secret badnest_issue_token
  cookie: !secret badnest_cookie
  region: us
fastdotcom:
  scan_interval:
      hours: 1
      minutes: 20
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret
lutron_caseta_pro:
  bridges:
    - host: !secret lutron_ip
      mac: !secret lutron_mac
      switch: [ 13, 16, 17, 22, 24, 27, 34, 36, 38, 41, 42 , 43, 44, 46]
stream:

########################################
###              INCLUDE             ###
########################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
alert: !include_dir_merge_named include/alert/
plant: !include_dir_merge_named include/plant/
input_boolean: !include_dir_merge_named include/input_boolean/
automation split: !include_dir_merge_list automation/
binary_sensor: !include_dir_merge_list include/binary_sensor/
sensor: !include_dir_merge_list include/sensor/
cover: !include_dir_merge_list include/cover/
vacuum: !include_dir_merge_list include/vacuum/
light: !include_dir_merge_list include/light/
media_player: !include_dir_merge_list include/media_player/
camera: !include_dir_merge_list include/camera/
notify: !include_dir_merge_list include/notify/
weather: !include_dir_merge_list include/weather/
tts: !include_dir_merge_list include/tts/
# switch: !include_dir_list include/switch/
# scene: !include_dir_list include/scene/
# lock: !include_dir_list include/lock/