- alias: Camis Bedroom Lights On
  description: Turn on Cami's Bedroom lights when motion detected.
  id: 4f93eb01-3f0e-4e73-956c-0a84012b7195
  mode: queued
  initial_state: true

  trigger:

    # motion detected in camis bedroom
    - platform: state
      entity_id: binary_sensor.camis_bedroom_wyze_motion
      from: 'off'
      to: 'on'

  condition:

    #  only continue if motion is not disabled?
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'

    # is camis home mode enabled?
    - condition: state
      entity_id: input_boolean.enable_camis_home_mode
      state: 'off'

    # must be within the times listed
    - condition: or
      conditions:

        # must not be between nap time
        - condition: time
          after: '08:00:00'
          before: '12:00:00'
          weekday:
            - sat
            - sun
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: time
          after: '15:30:00'
          before: '18:30:00'
          weekday:
            - sat
            - sun
            - mon
            - tue
            - wed
            - thu
            - fri

  action:

    - service: light.turn_on
      data_template:
        entity_id: light.camis_bedroom_ceiling


- alias: Camis Bedroom Lights Off
  description: Turn off Cami's Bedroom lights when NO motion detected.
  id: 3ee3b38a-7a72-4a3b-b1fc-2d1c84297035
  mode: single
  initial_state: true

  trigger:

    # no motion is detected for 15 minutes
    - platform: state
      entity_id: binary_sensor.camis_bedroom_wyze_motion
      to: 'off'
      for:
        minutes: 15

  condition:

    #  only continue if motion is not disabled?
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'

  action:

    - service: light.turn_off
      data:
        entity_id: light.camis_bedroom_ceiling
