- alias: Exterior Driveway Motion Detected On
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.exterior_esph_motion_driveway
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
    - data:
        title: "Motion Detected"
        message: "Driveway motion sensor triggered."
      service: notify.pushover_frank
    - service: homeassistant.turn_on
      data_template:
        entity_id:
          - switch.exterior_front_flood
          - switch.exterior_back_flood
    - delay:
        seconds: 3
    - condition: and
      conditions:
      - condition: state
        entity_id: switch.exterior_front_flood
        state: 'on'
      - condition: state
        entity_id: switch.exterior_back_flood
        state: 'on'
    - service: homeassistant.turn_on
      data_template:
        entity_id:
          - switch.exterior_front_garage
    - delay:
        seconds: 2
    - service: homeassistant.turn_on
      data_template:
        entity_id:
          - light.exterior_front_entry
    # - data:
    #     entity_id: camera.front_garage_camera
    #     filename: '/config/www/tmp/front_garage_camera.jpg'
    #   service: camera.snapshot

- alias: Exterior Driveway Motion Detected Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.exterior_esph_motion_driveway
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: 
          - switch.exterior_front_flood
          - switch.exterior_back_flood
          - switch.exterior_front_garage
          - light.exterior_front_entry
