- alias: Exterior Driveway Motion Detected On
  initial_state: true
  description: Run exterior sequence when driveway motion detected.
  id: 211ab2b1-d8af-4fd1-8b39-0338e7c14120
  mode: single

  trigger:

    # trigger when motion detected on the driveway
    - platform: state
      entity_id: binary_sensor.exterior_esph_motion_driveway
      from: 'off'
      to: 'on'

  condition:

    #  only continue if motion is not disabled
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'

  action:

    # notify frank when motion is detected
    - service: notify.pushover_frank
      data:
        title: "Motion Detected"
        message: "Driveway motion sensor triggered."

    # turn on the flood lights
    - service: homeassistant.turn_on
      data_template:
        entity_id:
          - switch.exterior_front_flood
          - switch.exterior_back_flood

    # wait 3 seconds to make sure the lights are on
    - delay:
        seconds: 3

    # only continue if both flood lights are on
    - condition: and
      conditions:

      - condition: state
        entity_id: switch.exterior_front_flood
        state: 'on'

      - condition: state
        entity_id: switch.exterior_back_flood
        state: 'on'

    # turn on the exterior garage lights
    - service: homeassistant.turn_on
      data_template:
        entity_id:
          - switch.exterior_front_garage

    # wait two more seconds to mimic presence
    - delay:
        seconds: 2

    # turn on exterior entry light
    - service: homeassistant.turn_on
      data_template:
        entity_id:
          - light.exterior_front_entry

    # - data:
    #     entity_id: camera.front_garage_camera
    #     filename: '/config/www/tmp/front_garage_camera.jpg'
    #   service: camera.snapshot

- alias: Exterior Driveway Motion Detected Off
  initial_state: true
  description: Turn off outdoor lights when no driveway motion detected for ten minutes.
  id: a984fdbf-c282-4482-9548-43b50373513b
  mode: single

  trigger:

    # trigger when motion is off for ten minutes
    - platform: state
      entity_id: binary_sensor.exterior_esph_motion_driveway
      to: 'off'
      for:
        minutes: 10

  condition:

    # only continue if motion is not disabled
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'

  action:

    # turn off exterior lights when conditions are met
    - service: homeassistant.turn_off
      data_template:
        entity_id: 
          - switch.exterior_front_flood
          - switch.exterior_back_flood
          - switch.exterior_front_garage
          - light.exterior_front_entry
