- alias: Hallway Motion Lights On
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_cf6e
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.hallway_main

- alias: Hallway Motion Lights Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_cf6e
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.hallway_main
