- alias: Master Bathroom Toilet Motion Lights On
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_cdf9
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.master_bathroom_toilet

- alias: Master Bathroom Toilet Motion Lights Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_cdf9
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.master_bathroom_toilet