- alias: Playroom Lights On
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_cdea
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.playroom_main

- alias: Playroom Lights Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_cdea
      to: 'off'
      for:
        minutes: 60
  condition:
    - condition: state
      entity_id: input_boolean.disable_motion_automation
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.playroom_main
