- platform: template
  sensors:
    outside_temperature:
      friendly_name: "Outside Temperature"
      value_template: "{{ state_attr('weather.dark_sky', 'temperature') }}"
      unit_of_measurement: "°F"
    outside_humidity:
      friendly_name: "Outside Humidity"
      value_template: "{{ state_attr('weather.dark_sky', 'humidity') }}"
      unit_of_measurement: "%"
    outside_wind_speed:
      friendly_name: "Outside Wind Speed"
      value_template: "{{ state_attr('weather.dark_sky', 'wind_speed') }}"
      unit_of_measurement: "mi/h"
    count_sensors:
      friendly_name: 'Number of Sensors'
      entity_id: []
      value_template: >-
        {{ states.sensor | list | count }}
    count_automations:
      friendly_name: 'Number of Automations'
      entity_id: []
      value_template: >-
        {{ states.automation| list | count }}
    count_scripts:
      friendly_name: 'Number of Scripts'
      entity_id: []
      value_template: >
        {{ states.script | list | count }}
    count_binary_sensor:
      friendly_name: 'Number of Binary Sensors'
      entity_id: []
      value_template: >-
        {{ states.binary_sensor | list | count }}
    count_lights:
      friendly_name: 'Number of Lights'
      entity_id: []
      value_template: >
        {{ states.light | list | count }}
    count_switches:
      friendly_name: 'Number of Switches'
      entity_id: []
      value_template: >
        {{ states.switch | list | count }}
